USE [master]
GO
CREATE LOGIN [user] WITH PASSWORD=N'user', DEFAULT_DATABASE=[loginRN], CHECK_EXPIRATION=OFF,
CHECK_POLICY=OFF
GO

USE [loginRN]
GO
CREATE USER [user] FOR LOGIN [user]
GO
USE [loginRN]
GO
ALTER ROLE [db_owner] ADD MEMBER [user]
GO